/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 ./public/shoe-black-white.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/shoe-black-white.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0.015, -0.008, 0.005]} rotation={[2.683, -0.402, 2.364]}>
        <mesh geometry={nodes.model_2004.geometry} material={materials['Material.002']} />
        <mesh geometry={nodes.model_2004_1.geometry} material={materials['Material.001']} />
      </group>
    </group>
  )
}

useGLTF.preload('/shoe-black-white.glb')
